### ISSUE TITLE
UnboundLocalError: local variable 'best' referenced before assignment

### ISSUE THREAD

**Issue by pietheinstrengholt** [r0oth3x49/acloud-dl#1]
Thanks for creating this. I've tried the tool and for most courses it works. However for some I'm getting the error below. Any help is much appreciated.

```
Traceback (most recent call last):
  File "acloud-dl.py", line 213, in <module>
    main()
  File "acloud-dl.py", line 206, in main
    acloud.course_download(path=options.output, quality=options.quality)
  File "acloud-dl.py", line 126, in course_download
    lecture_best = lecture.get_quality(best_quality=lecture_best, streams=lecture_streams, requested=quality)
  File "/Users/piethein/Sites/acloud-dl/acloud/_shared.py", line 210, in get_quality
    if not best:
UnboundLocalError: local variable 'best' referenced before assignment
```

**Comment by r0oth3x49** [comment]
@pietheinstrengholt sorry for the late response and thanks for appreciation. i might need an account to reproduce the error and fix currently i don't have any account.
