### ISSUE TITLE
ImportError: No module named unidecode

### ISSUE THREAD

**Issue by aws25** [r0oth3x49/acloud-dl#10]
ABC-MacBook-Pro:acloud-dl def$ sudo python acloud-dl.py -c file_containing_cookie.txt
Password:
Traceback (most recent call last):
File "acloud-dl.py", line 7, in 
import acloud
File "/Users/def/Desktop/acloud-dl/acloud/init.py", line 32, in 
from ._acloud import courses
File "/Users/def/Desktop/acloud-dl/acloud/_acloud.py", line 26, in 
from ._internal import InternCloudGuruCourse as CloudGuru
File "/Users/def/Desktop/acloud-dl/acloud/_internal.py", line 30, in 
from ._extract import CloudGuru
File "/Users/def/Desktop/acloud-dl/acloud/_extract.py", line 45, in 
from ._sanitize import (
File "/Users/def/Desktop/acloud-dl/acloud/_sanitize.py", line 10, in 
from unidecode import unidecode
ImportError: No module named unidecode

**Comment by aws25** [comment]
"Inspect Element" is grayed out

**Comment by r0oth3x49** [comment]
> 
> 
> "Inspect Element" is grayed out

what do you mean i don't get this point?

**Comment by r0oth3x49** [comment]
you should install requirements 1st to run the tool and the cookie file also doesn't seems good.
