### ISSUE TITLE
Selamun Aleykum

### ISSUE THREAD

**Issue by virgilpostell** [r0oth3x49/acloud-dl#37]
```
select course number between (1/75/all): 21
[*] : Course 'Go Serverless with a Graph Database'.
Traceback (most recent call last):on ..
  File "acloud-dl.py", line 326, in <module>
    main()
  File "acloud-dl.py", line 319, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 201, in course_download
    course = course.get_course(keep_alive=download_all)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_shared.py", line 88, in get_course
    self._process_course(keep_alive=keep_alive)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_internal.py", line 69, in _process_course
    self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_internal.py", line 79, in __init__
    super(InternCloudGuruCourse, self).__init__()
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_shared.py", line 109, in __init__
    self._fetch_course()
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_internal.py", line 85, in _fetch_course
    self._info              =       self._real_extract(course_id=course_id)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_extract.py", line 356, in _real_extract
    'lectures' : self._extract_lectures(lectures)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_extract.py", line 289, in _extract_lectures
    sources = self._extract_sources(sources)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_extract.py", line 186, in _extract_sources
    for entry in sources:
TypeError: 'NoneType' object is not iterable
```

```
[*] : Course 'AWS Certified Advanced Networking - Specialty 2020'.
Traceback (most recent call last):on ..
  File "acloud-dl.py", line 326, in <module>
    main()
  File "acloud-dl.py", line 319, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 201, in course_download
    course = course.get_course(keep_alive=download_all)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_shared.py", line 88, in get_course
    self._process_course(keep_alive=keep_alive)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_internal.py", line 69, in _process_course
    self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_internal.py", line 79, in __init__
    super(InternCloudGuruCourse, self).__init__()
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_shared.py", line 109, in __init__
    self._fetch_course()
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_internal.py", line 85, in _fetch_course
    self._info              =       self._real_extract(course_id=course_id)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_extract.py", line 356, in _real_extract
    'lectures' : self._extract_lectures(lectures)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_extract.py", line 289, in _extract_lectures
    sources = self._extract_sources(sources)
  File "C:\Users\Administrator\Downloads\acloud-dl-master\acloud\_extract.py", line 186, in _extract_sources
    for entry in sources:
TypeError: 'NoneType' object is not iterable
```

**Comment by r0oth3x49** [comment]
@virgilpostell i don't have a valid account to test i might need your account creds you can email me `nasir251292@gmail.com`

**Comment by virgilpostell** [comment]
> nasir251292@gmail.com

email send!

**Comment by r0oth3x49** [comment]
> 
> 
> > [nasir251292@gmail.com](mailto:nasir251292@gmail.com)
> 
> email send!

you sure you send the your creds to above email i didn't received anything yet. i 'm closing the issue
