### ISSUE TITLE
Can't download latest course 

### ISSUE THREAD

**Issue by sohel4r** [r0oth3x49/acloud-dl#38]
For example: AWS Certified Solutions Architect Associate 2020

Here is the error:
Traceback (most recent call last):on .. 
  File "acloud-dl.py", line 326, in <module>
    main()
  File "acloud-dl.py", line 319, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 201, in course_download
    course = course.get_course(keep_alive=download_all)
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_shared.py", line 88, in get_course
    self._process_course(keep_alive=keep_alive)
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_internal.py", line 69, in _process_course
    self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_internal.py", line 79, in __init__
    super(InternCloudGuruCourse, self).__init__()
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_shared.py", line 109, in __init__
    self._fetch_course()
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_internal.py", line 85, in _fetch_course
    self._info              =       self._real_extract(course_id=course_id)        
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_extract.py", line 356, in _real_extract
    'lectures' : self._extract_lectures(lectures)
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_extract.py", line 289, in _extract_lectures
    sources = self._extract_sources(sources)
  File "/home/sk/1TB/Tutorials/AWS/acloud-dl/acloud/_extract.py", line 186, in _extract_sources
    for entry in sources:
TypeError: 'NoneType' object is not iterable

**Comment by sgodbehe** [comment]
Adding some more info on this problem:

`
              __                __          ____
  ____ ______/ /___  __  ______/ /     ____/ / /
 / __ `/ ___/ / __ \/ / / / __  /_____/ __  / /
/ /_/ / /__/ / /_/ / /_/ / /_/ /_____/ /_/ / /
\__,_/\___/_/\____/\__,_/\__,_/      \__,_/_/

                                 Version : 0.1
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[*] : Downloading accessible courses information .. (done)
[1] : AWS Certified Cloud Practitioner 2020
[2] : AWS Certified Solutions Architect Associate 2020
[3] : Introduction to AWS
[4] : Introduction to Cloud Computing
[?] : select course number between (1/4/all): 2

[*] : Course 'AWS Certified Solutions Architect Associate 2020'.
Traceback (most recent call last):on ..
  File "acloud-dl.py", line 326, in <module>
    main()
  File "acloud-dl.py", line 319, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 201, in course_download
    course = course.get_course(keep_alive=download_all)
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_shared.py", line 88, in get_course
    self._process_course(keep_alive=keep_alive)
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_internal.py", line 69, in _process_course
    self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_internal.py", line 79, in __init__
    super(InternCloudGuruCourse, self).__init__()
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_shared.py", line 109, in __init__
    self._fetch_course()
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_internal.py", line 85, in _fetch_course
    self._info              =       self._real_extract(course_id=course_id)
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_extract.py", line 356, in _real_extract
    'lectures' : self._extract_lectures(lectures)
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_extract.py", line 289, in _extract_lectures
    sources = self._extract_sources(sources)
  File "C:\Users\sgodbehe\Videos\acloud-dl-master\acloud\_extract.py", line 186, in _extract_sources
    for entry in sources:
TypeError: 'NoneType' object is not iterable`

**Comment by r0oth3x49** [comment]
@sohel4r will be fixed in next commit, will push on weekend
