### ISSUE TITLE
'Nonetype' object is not iterable

### ISSUE THREAD

**Issue by anuppoudel54** [r0oth3x49/acloud-dl#40]
Not able to download courses

**Comment by sarpdoruk** [comment]
Same here;

```
Traceback (most recent call last):on ..
  File "acloud-dl.py", line 326, in <module>
    main()
  File "acloud-dl.py", line 319, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 201, in course_download
    course = course.get_course(keep_alive=download_all)
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_shared.py", line 88, in get_course
    self._process_course(keep_alive=keep_alive)
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_internal.py", line 69, in _process_course
    self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_internal.py", line 79, in __init__
    super(InternCloudGuruCourse, self).__init__()
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_shared.py", line 109, in __init__
    self._fetch_course()
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_internal.py", line 85, in _fetch_course
    self._info              =       self._real_extract(course_id=course_id)
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_extract.py", line 356, in _real_extract
    'lectures' : self._extract_lectures(lectures)
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_extract.py", line 289, in _extract_lectures
    sources = self._extract_sources(sources)
  File "/Users/sarpdoruk/Downloads/acloud-dl-master/acloud/_extract.py", line 186, in _extract_sources
    for entry in sources:
TypeError: 'NoneType' object is not iterable
```
