### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by mavericksrini** [r0oth3x49/acloud-dl#53]
Traceback (most recent call last):
  File "acloud-dl.py", line 332, in <module>
    main()
  File "acloud-dl.py", line 325, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 241, in course_download
    self.download_lectures_only(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=lecture_index, lectures_count=lectures_count, lecture_assets=lecture_assets, lecture_subs=lecture_subs, filepath=filepath)
  File "acloud-dl.py", line 174, in download_lectures_only
    self.download_lectures(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, filepath=filepath)
  File "acloud-dl.py", line 159, in download_lectures
    retval = lecture_best.download(filepath=filepath, quiet=True, callback=self.show_progress)
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_shared.py", line 470, in download
    os.rename(temp_filepath, filepath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\@@@@\\Downloads\\acloud-dl-master\\Red Hat Certified Specialist in Linux Diagnostics and Troubleshooting Exam Prep (RH342 )\\07 Diagnose application issues\\001 Identify library dependencies for third-party software.mp4.part' -> 'C:\\Users\\@@@@\\Downloads\\acloud-dl-master\\Red Hat Certified Specialist in Linux Diagnostics and Troubleshooting Exam Prep (RH342 )\\07 Diagnose application issues\\001 Identify library dependencies for third-party software.mp4'

**Comment by mavericksrini** [comment]
File "acloud-dl.py", line 332, in <module>
    main()
  File "acloud-dl.py", line 325, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 209, in course_download
    course = course.get_course(keep_alive=download_all)
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_shared.py", line 88, in get_course
    self._process_course(keep_alive=keep_alive)
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_internal.py", line 69, in _process_course
    self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_internal.py", line 79, in __init__
    super(InternCloudGuruCourse, self).__init__()
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_shared.py", line 109, in __init__
    self._fetch_course()
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_internal.py", line 85, in _fetch_course
    self._info              =       self._real_extract(course_id=course_id)
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_extract.py", line 494, in _real_extract
    'lectures' : self._extract_lectures(lectures)
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_extract.py", line 429, in _extract_lectures
    streams = self._fetch_hls_streams_by_content_ids(contentid_list)
  File "C:\Users\@@@@\Downloads\acloud-dl-master\acloud\_extract.py", line 316, in _fetch_hls_streams_by_content_ids
    _id = entry.get("contentId")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by r0oth3x49** [comment]
@mavericksrini have pushed a fix for the 1st error for the 2nd i might need an account.

**Comment by r0oth3x49** [comment]
as i don't see any response from you i 'm closing the issue.
