### ISSUE TITLE
Can not able to get course list , TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by maheshmalva** [r0oth3x49/acloud-dl#54]
python acloud-dl.py -c file.txt --info

              __                __          ____
  ____ ______/ /___  __  ______/ /     ____/ / /
 / __ `/ ___/ / __ \/ / / / __  /_____/ __  / /
/ /_/ / /__/ / /_/ / /_/ / /_/ /_____/ /_/ / /
\__,_/\___/_/\____/\__,_/\__,_/      \__,_/_/

                                 Version : 0.1
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

Traceback (most recent call last):es information ..
  File "acloud-dl.py", line 332, in <module>
    main()
  File "acloud-dl.py", line 322, in main
    acloud.course_list_down()
  File "acloud-dl.py", line 31, in course_list_down
    courses = acloud.courses(cookies=self.cookies)
  File "C:\acloud-dl-master\acloud\_acloud.py", line 35, in courses
    return CloudGuru(cookies, basic, callback).courses
  File "C:\acloud-dl-master\acloud\_internal.py", line 46, in __init__
    super(InternCloudGuruCourses, self).__init__(*args, **kwargs)
  File "C:\acloud-dl-master\acloud\_shared.py", line 56, in __init__
    self._fetch_courses()
  File "C:\acloud-dl-master\acloud\_internal.py", line 55, in _fetch_courses
    self._courses = [InternCloudGuruCourseDownload(c, self) for c in courses]
TypeError: 'NoneType' object is not iterable

**Comment by r0oth3x49** [comment]
what's inside `file.txt`? would you like to explain the issue properly

**Comment by maheshmalva** [comment]
@r0oth3x49  Thanks , It's working now.
