### ISSUE TITLE
Getting NoneType Error in specific course

### ISSUE THREAD

**Issue by Dragon0708** [r0oth3x49/acloud-dl#56]
>python acloud-dl.py -c cookies.txt
===========================

[*] : Course 'Python 3 Scripting for System Administrators'.    <====
[*] : Downloading course information .. \Traceback (most recent call last):
  File "acloud-dl.py", line 332, in <module>
    main()
  File "acloud-dl.py", line 325, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 209, in course_download
    course = course.get_course(keep_alive=download_all)
  File "C:\\acloud\_shared.py", line 88, in get_course
    self._process_course(keep_alive=keep_alive)
  File "C:\\acloud\_internal.py", line 69, in _process_course
    self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
  File "C:\\acloud\_internal.py", line 79, in __init__
    super(InternCloudGuruCourse, self).__init__()
  File "C:\\acloud\_shared.py", line 109, in __init__
    self._fetch_course()
  File "C:\\acloud\_internal.py", line 85, in _fetch_course
    self._info              =       self._real_extract(course_id=course_id)
  File "C:\\acloud\_extract.py", line 504, in _real_extract
    'lectures' : self._extract_lectures(lectures)
  File "C:\\acloud\_extract.py", line 439, in _extract_lectures
    streams = self._fetch_hls_streams_by_content_ids(contentid_list)
  File "C:\\acloud\_extract.py", line 326, in _fetch_hls_streams_by_content_ids
    _id = entry.get("contentId")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by trickycloud** [comment]
ya, I am facing this problem also...
