### ISSUE TITLE
Fails for some videos, possibly due to some character in name

### ISSUE THREAD

**Issue by tripperaf** [r0oth3x49/acloud-dl#73]
[+] : Downloaded  (001 Understanding - Red Hat.html)
Traceback (most recent call last):
  File "acloud-dl.py", line 332, in <module>
    main()
  File "acloud-dl.py", line 325, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 241, in course_download
    self.download_lectures_only(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=lecture_index, lectures_count=lectures_count, lecture_assets=lecture_assets, lecture_subs=lecture_subs, filepath=filepath)
  File "acloud-dl.py", line 176, in download_lectures_only
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath)
  File "acloud-dl.py", line 135, in download_assets
    assets.download(filepath=filepath, quiet=True, callback=self.show_progress)
  File "C:\Users\AppData\Local\Programs\Python\Python37\acloud\_shared.py", line 853, in download
    return self._write_external_links(filepath)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\acloud\_shared.py", line 769, in _write_external_links
    with open("{}".format(filename), "a", encoding="utf-8") as f:
OSError: [Errno 22] Invalid argument: '\\\\?\\\\\\?\\C:\\Users\\AppData\\Local\\Programs\\Python\\Python37\\Hands-on with \\03 Managing \\001  Linux 8 - Images.txt'

**Comment by r0oth3x49** [comment]
I might need an account to reproduce and fix the issue, You can email me your creds on `nasir251292@gmail.com` if you don't have any issue with sharing creds otherwise i can't fix the issue as i don't have any account on acloud as of yet

**Comment by r0oth3x49** [comment]
You should download it to a short path like `E:\\tuts` or disable path limit in windows
