### ISSUE TITLE
download error: Invalid argument

### ISSUE THREAD

**Issue by supersjimmie** [r0oth3x49/acloud-dl#81]
After the latest fix, I am able to download may video's.
They are downloaded as ```.VIDEO_AUDIO```, which I can then open in e.g. VLC. (or rename them to .mp4 and open).
However, after downloading a bunch of AWS video's it stopped:

```
[*] : Lecture(s) : (9 of 15)
[*] : Downloading (009 Optimizing S3 Performance)
[*] : 74.95MB/74.95MB 100.00% |##############################| 5.29MB/s
[+] : Downloaded  (009 Optimizing S3 Performance)
Traceback (most recent call last):
  File "C:\Users\User\Downloads\acloudguru\acloud-dl\acloud-dl.py", line 332, in <module>
    main()
  File "C:\Users\User\Downloads\acloudguru\acloud-dl\acloud-dl.py", line 325, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "C:\Users\User\Downloads\acloudguru\acloud-dl\acloud-dl.py", line 241, in course_download
    self.download_lectures_only(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=lecture_index, lectures_count=lectures_count, lecture_assets=lecture_assets, lecture_subs=lecture_subs, filepath=filepath)
  File "C:\Users\User\Downloads\acloudguru\acloud-dl\acloud-dl.py", line 176, in download_lectures_only
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath)
  File "C:\Users\User\Downloads\acloudguru\acloud-dl\acloud-dl.py", line 135, in download_assets
    assets.download(filepath=filepath, quiet=True, callback=self.show_progress)
  File "C:\Users\User\Downloads\acloudguru\acloud-dl\acloud\_shared.py", line 853, in download
    return self._write_external_links(filepath)
  File "C:\Users\User\Downloads\acloudguru\acloud-dl\acloud\_shared.py", line 769, in _write_external_links
    with open("{}".format(filename), "a", encoding="utf-8") as f:
OSError: [Errno 22] Invalid argument: '\\\\?\\\\\\?\\C:\\Users\\User\\Downloads\\acloudguru\\acloud-dl\\AWS Certified Solutions Architect - Associate (SAA-C02)\\05 Simple Storage Service (S3)\\009 For Amazon S3 request rates whats the difference between prefixes and nested folders How many prefixes can I have in an S3 bucket.txt'
```
(which is part of AWS Certified Solutions Architect - Associate (SAA-C02))

**Comment by goforgold** [comment]
I am seeing the exact same error. Any solution so far?
